import { expect, test, type Page } from "@playwright/test";
async function demoLogin(page: Page, label: string) { await page.goto("/login"); await page.getByRole("button", { name: label, exact: true }).click(); await expect(page).toHaveURL((url) => url.pathname === "/dashboard"); }
async function expectNoOverflow(page: Page) { const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth })); expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth); }
test("anonymous users are redirected to sign in and receive security headers", async ({ page }) => { const response = await page.goto("/dashboard"); await expect(page).toHaveURL((url) => url.pathname === "/login"); await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible(); const headers = response?.headers() || {}; expect(headers["x-content-type-options"]).toBe("nosniff"); expect(headers["x-frame-options"]).toBe("DENY"); });
test("student dashboard and protected navigation render without browser errors", async ({ page }) => { const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await demoLogin(page, "Student"); await expect(page.getByRole("heading", { name: /Good afternoon/ })).toBeVisible(); const opportunitiesLink = page.getByRole("link", { name: "Opportunities", exact: true }); await expect(opportunitiesLink).toBeVisible(); await opportunitiesLink.click(); await expect(page.getByRole("heading", { name: "Find work that moves you forward." })).toBeVisible(); await expectNoOverflow(page); expect(errors).toEqual([]); });
test("industry sees pipeline but cannot open institution analytics", async ({ page }) => { await demoLogin(page, "Industry"); await expect(page.getByRole("heading", { name: "Your talent workspace" })).toBeVisible(); await page.goto("/analytics"); await expect(page).toHaveURL((url) => url.pathname === "/forbidden"); });
test("responsive routes have no horizontal document overflow", async ({ page }) => { await demoLogin(page, "Student"); for (const size of [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 900 }, { width: 390, height: 844 }]) { await page.setViewportSize(size); await page.goto("/dashboard"); await expect(page.getByRole("heading", { name: /Good afternoon/ })).toBeVisible(); await expectNoOverflow(page); await page.goto("/opportunities"); await expectNoOverflow(page); } });
test("academician can discover faculty opportunities", async ({ page }) => { await demoLogin(page, "Academician"); await page.goto("/opportunities"); await expect(page.getByText("Faculty Industry Immersion: Responsible AI")).toBeVisible(); });
test("student completes a server-scored assessment", async ({ page }) => { await demoLogin(page, "Student"); await page.goto("/assessment/start"); for (const answer of ["Confident", "A database uniqueness constraint", "Usually", "Usually"]) { await page.getByRole("button", { name: answer, exact: true }).click(); } await page.getByRole("button", { name: "Submit assessment" }).click(); await expect(page.getByRole("heading", { name: "Your result is ready to review." })).toBeVisible(); });
test("captures reviewed desktop and mobile dashboard states", async ({ page }) => { await demoLogin(page, "Student"); await page.setViewportSize({ width: 1440, height: 900 }); await page.screenshot({ path: "test-results/dashboard-desktop.png", fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/dashboard"); await expectNoOverflow(page); await page.screenshot({ path: "test-results/dashboard-mobile.png", fullPage: true }); });
